/* Per evitare potenziali problemi di perdita di dati, si consiglia di esaminare dettagliatamente lo script prima di eseguirlo al di fuori del contesto di Progettazione database.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tmp_TabStatisticheTmp
	(
	Prog bigint NOT NULL IDENTITY (1, 1),
	IdStazione int NOT NULL,
	IdCamera bigint NOT NULL,
	DataRiferimentoTurno date NOT NULL,
	NomeTurno smallint NOT NULL,
	IdFormato varchar(50) NOT NULL,
	TimeStamp datetime NOT NULL,
	TEST_INTEGRITA_AREA float(53) NULL,
	TEST_INTEGRITA_DELTA float(53) NULL,
	TEST_DIMENSIONE_DIAMETRO float(53) NULL,
	TEST_DIMENSIONE_CIRCOLARITA float(53) NULL,
	TEST_DIMENSIONE_W float(53) NULL,
	TEST_DIMENSIONE_H float(53) NULL,
	TEST_CREPE_LEN float(53) NULL,
	TEST_DISEGNI_PRESENZA_AREA float(53) NULL,
	TEST_DISEGNI_MACCHIE_GROSSE_AREA_MAX float(53) NULL,
	TEST_COLORE_DIST float(53) NULL,
	TEST_COLORE_DIST_2 float(53) NULL,
	TEST_COLORE_2_AREA float(53) NULL,
	TEST_SBORDAMENTO_AREA_MAX float(53) NULL,
	TEST_DIMENSIONE_ALTEZZA float(53) NULL,
	TEST_DIMENSIONE_LATO_W float(53) NULL,
	TEST_DIMENSIONE_LATO_H float(53) NULL,
	TEST_RAKE_DIMENSIONE_LATO_V_0 float(53) NULL,
	TEST_RAKE_DIMENSIONE_LATO_V_1 float(53) NULL,
	TEST_RAKE_DIMENSIONE_LATO_V_2 float(53) NULL,
	TEST_RAKE_DIMENSIONE_LATO_V_3 float(53) NULL,
	TEST_RAKE_DIMENSIONE_LATO_V_4 float(53) NULL,
	TEST_RAKE_DIMENSIONE_LATO_H_0 float(53) NULL,
	TEST_RAKE_DIMENSIONE_LATO_H_1 float(53) NULL,
	TEST_RAKE_DIMENSIONE_LATO_H_2 float(53) NULL,
	TEST_RAKE_DIMENSIONE_LATO_H_3 float(53) NULL,
	TEST_RAKE_DIMENSIONE_LATO_H_4 float(53) NULL,
	ALG_OK bit NOT NULL,
	ALLINEAMENTO_OK bit NULL,
	TEST_INTEGRITA_OK bit NULL,
	TEST_DIMENSIONE_OK bit NULL,
	TEST_CREPE_OK bit NULL,
	TEST_DISEGNI_OK bit NULL,
	TEST_COLORE_OK bit NULL,
	TEST_COLORE_2_OK bit NULL,
	TEST_SBORDAMENTO_OK bit NULL,
	TEST_ALTEZZA_OK bit NULL,
	TEST_DIMENSIONE_LATO_OK bit NULL,
	TEST_RAKE_DIMENSIONE_LATO_OK bit NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_TabStatisticheTmp SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.Tmp_TabStatisticheTmp ADD CONSTRAINT
	DF_TabStatisticheTmp_IdStazione DEFAULT 0 FOR IdStazione
GO
SET IDENTITY_INSERT dbo.Tmp_TabStatisticheTmp ON
GO
IF EXISTS(SELECT * FROM dbo.TabStatisticheTmp)
	 EXEC('INSERT INTO dbo.Tmp_TabStatisticheTmp (Prog, IdCamera, DataRiferimentoTurno, NomeTurno, IdFormato, TimeStamp, TEST_INTEGRITA_AREA, TEST_INTEGRITA_DELTA, TEST_DIMENSIONE_DIAMETRO, TEST_DIMENSIONE_CIRCOLARITA, TEST_DIMENSIONE_W, TEST_DIMENSIONE_H, TEST_CREPE_LEN, TEST_DISEGNI_PRESENZA_AREA, TEST_DISEGNI_MACCHIE_GROSSE_AREA_MAX, TEST_COLORE_DIST, TEST_COLORE_DIST_2, TEST_COLORE_2_AREA, TEST_SBORDAMENTO_AREA_MAX, TEST_DIMENSIONE_ALTEZZA, TEST_DIMENSIONE_LATO_W, TEST_DIMENSIONE_LATO_H, TEST_RAKE_DIMENSIONE_LATO_V_0, TEST_RAKE_DIMENSIONE_LATO_V_1, TEST_RAKE_DIMENSIONE_LATO_V_2, TEST_RAKE_DIMENSIONE_LATO_V_3, TEST_RAKE_DIMENSIONE_LATO_V_4, TEST_RAKE_DIMENSIONE_LATO_H_0, TEST_RAKE_DIMENSIONE_LATO_H_1, TEST_RAKE_DIMENSIONE_LATO_H_2, TEST_RAKE_DIMENSIONE_LATO_H_3, TEST_RAKE_DIMENSIONE_LATO_H_4, ALG_OK, ALLINEAMENTO_OK, TEST_INTEGRITA_OK, TEST_DIMENSIONE_OK, TEST_CREPE_OK, TEST_DISEGNI_OK, TEST_COLORE_OK, TEST_COLORE_2_OK, TEST_SBORDAMENTO_OK, TEST_ALTEZZA_OK, TEST_DIMENSIONE_LATO_OK, TEST_RAKE_DIMENSIONE_LATO_OK)
		SELECT Prog, IdCamera, DataRiferimentoTurno, NomeTurno, IdFormato, TimeStamp, TEST_INTEGRITA_AREA, TEST_INTEGRITA_DELTA, TEST_DIMENSIONE_DIAMETRO, TEST_DIMENSIONE_CIRCOLARITA, TEST_DIMENSIONE_W, TEST_DIMENSIONE_H, TEST_CREPE_LEN, TEST_DISEGNI_PRESENZA_AREA, TEST_DISEGNI_MACCHIE_GROSSE_AREA_MAX, TEST_COLORE_DIST, TEST_COLORE_DIST_2, TEST_COLORE_2_AREA, TEST_SBORDAMENTO_AREA_MAX, TEST_DIMENSIONE_ALTEZZA, TEST_DIMENSIONE_LATO_W, TEST_DIMENSIONE_LATO_H, TEST_RAKE_DIMENSIONE_LATO_V_0, TEST_RAKE_DIMENSIONE_LATO_V_1, TEST_RAKE_DIMENSIONE_LATO_V_2, TEST_RAKE_DIMENSIONE_LATO_V_3, TEST_RAKE_DIMENSIONE_LATO_V_4, TEST_RAKE_DIMENSIONE_LATO_H_0, TEST_RAKE_DIMENSIONE_LATO_H_1, TEST_RAKE_DIMENSIONE_LATO_H_2, TEST_RAKE_DIMENSIONE_LATO_H_3, TEST_RAKE_DIMENSIONE_LATO_H_4, ALG_OK, ALLINEAMENTO_OK, TEST_INTEGRITA_OK, TEST_DIMENSIONE_OK, TEST_CREPE_OK, TEST_DISEGNI_OK, TEST_COLORE_OK, TEST_COLORE_2_OK, TEST_SBORDAMENTO_OK, TEST_ALTEZZA_OK, TEST_DIMENSIONE_LATO_OK, TEST_RAKE_DIMENSIONE_LATO_OK FROM dbo.TabStatisticheTmp WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_TabStatisticheTmp OFF
GO
DROP TABLE dbo.TabStatisticheTmp
GO
EXECUTE sp_rename N'dbo.Tmp_TabStatisticheTmp', N'TabStatisticheTmp', 'OBJECT' 
GO
ALTER TABLE dbo.TabStatisticheTmp ADD CONSTRAINT
	PK_TabStatisticheTmp PRIMARY KEY CLUSTERED 
	(
	Prog
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
COMMIT